version: "3.8"

services:
  app:
    container_name: pylonsample
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${CONTAINER_PORT}:8000"
    restart: always
    # Enable this if sqlserver is enable
    # depends_on:
    #   - sqlserver

  # Enable this if need to run this container
  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     SA_PASSWORD: "DB_Password"
  #     ACCEPT_EULA: "Y"
  #   ports:
  #     - "1433:1433"